### ISSUE TITLE
Reports.py import amazonmws error

### ISSUE THREAD

**Issue by sakshamgulati** [cpburnz/python-amazon-mws#6]
What seems to be a simple  pip install functionality, doesn't seem to work. Has amazonmws.mws been changed to mws and has it lost functionality for reports.py??

import six # Python2/Python3 compatibility library.
import datetime
import amazonmws.mws
from amazonmws.util import datetime_to_iso8601, encode_string, is_sequence, marketplace_args

**Comment by cpburnz** [comment]
The problem appears to be that *six* is not properly marked as a dependency. In the mean time you can install [six](https://pypi.org/project/six/) and that will solve the issue.

**Comment by cpburnz** [comment]
v1.0.3 is now available.
